Add new cli documentation
workarea-commerce/workarea pull request #576
Opened 2020-12-15 20:04 UTC by eric-pigeon

2020-12-16 13:17 UTC, bencrouse requested changes
A couple comments:
* Do we need `docs/source/cli-old.html.md` for anything? Let's remove if it's cruft, we have it in the git history if we need to revisit.
* Conventionally, the docs article files use dashes, not underscores, can you update for consistency?
* It would be easy and consistent for branding to do find and replace `workarea-commerce environments` => `Workarea Commerce Cloud environments`

2020-12-16 13:17 UTC, bencrouse commented on docs/source/cli/workareactl.html.md
> +A tool for interacting with workarea-commerce environments
```suggestion
A tool for interacting with Workarea Commerce Cloud environments
```

2020-12-16 13:17 UTC, bencrouse commented on docs/source/cli/workareactl_edit.html.md
> +edit various aspects of the environment
```suggestion
Edit various aspects of the environment
```

2020-12-16 13:17 UTC, bencrouse commented on docs/source/cli/workareactl_edit.html.md
> +edit various aspects of the environment
```suggestion
Edit various aspects of the environment
```

2020-12-16 13:17 UTC, bencrouse commented on docs/source/cli/workareactl_edit_proxy.html.md
> +edit the proxy
```suggestion
Edit the proxy
```

2020-12-16 13:17 UTC, bencrouse commented on docs/source/cli/workareactl_edit_proxy.html.md
> +edit the proxy
```suggestion
Edit the proxy
```

2020-12-16 13:17 UTC, bencrouse commented on docs/source/cli/workareactl_edit_secrets.html.md
> +edit the secrets
```suggestion
Edit the secrets
```

2020-12-16 13:17 UTC, bencrouse commented on docs/source/cli/workareactl_edit_secrets.html.md
> +edit the secrets
```suggestion
Edit the secrets
```

2020-12-16 13:17 UTC, bencrouse commented on docs/source/index.html.erb
> +          Information about our hosted commerce cloud solution.
```suggestion
          Information about our hosted Commerce Cloud solution.
```

2020-12-16 20:11 UTC, eric-pigeon commented
I am still linking to the old cli docs, I think we can remove it after everyone is migrated to the new cli.

2020-12-17 13:55 UTC, bencrouse approved these changes
@mcfearsome @MMartyn @wmferri do you guys want to take a look before I merge this?

2020-12-17 14:07 UTC, MMartyn approved these changes

2020-12-17 15:16 UTC, merged